### ISSUE TITLE
Proper entitlement checks, no beatsaver data

### ISSUE THREAD

**Issue by michael-r-elp** [EnderdracheLP/MultiplayerCore.Quest#10]
I should do some proper Entitlement checks that use the data sent by the players instead of querying beatsaver which can only give me some basic info.

One way would be by finding the map data during entitlement checking, possibly going through all players, would probably cause issues at high player counts
Another way would be to write per map per difficulty requirements into a vector or something for ease of access, problem here could potentially be memory consumption with large map counts

I'll eventually get around to trying some approaches out

**Comment by cubicgraphics** [comment]
I think this may have been solved as the server now correctly gets and shares player entitlements between players when you select a song,
map selected packet sent to server -> server send a get entitlement packet to everyone -> server then sends each player the entitlement data for the map they have selected and will send more if there entitlement changes at any point.

**Comment by michael-r-elp** [comment]
Yeah, will close that, don't think I've heard about any entitlement issues since then, and I doubt I would have any reason to add this functionality now
