### ISSUE TITLE
[Feature Request]: Update to 1.35 or 1.37

### ISSUE THREAD

**Issue by GunnableScum** [EnderdracheLP/MultiplayerCore.Quest#30]
### Is your feature request related to a problem?

I play beat saber regularily with a few friends of mine. We're forced to be stuck with the built-in songs from OST 1-7 and Extras, however we'd like to be able to play custom songs. I have tried downgrading to 1.28 with QAVS and using Quest Patcher to add mods to it, however it basically crashes every 2 minutes which is the biggest inconvenience you can have.

### Describe the solution you'd like

I would appreciate an upgrade to version 1.35 or 1.37, as it's more stable and newer.

### Describe alternatives you've considered

I have considered using PCVR with my Quest, however my quest actually has a burn-in in it's charging port which would make it unsuitable to be used with Steam VR or Quest Link as it has caused a pretty bad wiggle contact.

### Additional context

No, no additional context needed. Only thing I do have is that you should not strain yourself if you do consider writing an upgrade. I wish you a nice day! :)

### Device

Quest 2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michael-r-elp** [comment]
An Update to 1.37.0 for Quest is in the works and currently in testing for BeatTogether patreons.
See [Branch dev/1.37](https://github.com/EnderdracheLP/MultiplayerCore.Quest/tree/dev/1.37).

**Comment by GunnableScum** [comment]
Hey, nice! Do you have a possible estimate for when it could release?

**Comment by michael-r-elp** [comment]
The current plan is sometime this month, if there are no major hold-ups and all bugs can be fixed.

**Comment by GunnableScum** [comment]
Great, that's all I wanted to know. I wish you the best of luck! Have a nice day!
